site_name: "Generative AI: From Start to Surrender"

nav:
  - Introduction:
      - Terms: "book/chapter 1 Introduction/1.1 terminology.md"
      - Fourier Transform: "book/chapter 1 Introduction/1.2 fourier transform.md"
      - Signal Processing: "book/chapter 1 Introduction/1.3 signal processing.md"
  - GANs:
      - PGGAN: "book/chapter 3 GAN/2.2 pggan/paper.md"
      - StyleGAN: "book/chapter 3 GAN/2.3 stylegan/paper.md"
      - StyleGAN2: "book/chapter 3 GAN/2.4 stylegan2/paper.md"
      - StyleGAN3: "book/chapter 3 GAN/2.5 stylegan 3/paper.md"

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js