site_name: "Generative AI: From Start to Surrender"
nav:
  - "Home": index.md
  - Introduction:
      - Terms: "book/chapter1_Introduction/1.1terminology.md"
      - Fourier Transform: "book/chapter1_Introduction/1.2fourier_transform.md"
      - Signal Processing: "book/chapter1_Introduction/1.3signal_processing.md"
      - Statistics: "book/chapter1_Introduction/1.4statistics.md"
      - SDE: "book/chapter1_Introduction/1.5SDE.md"
      - Tutorials: "book/chapter1_Introduction/tutorials.md"
  - VAE:
      - Introduction: "book/chapter2_VAE/2.1introduction.md"
  - GANs:
      - From GAN to PGGAN: "book/chapter3_GAN/3.1from_gan_to_stylegan/paper.md"
      - StyleGAN: "book/chapter3_GAN/3.3stylegan/paper.md"
      - StyleGAN2: "book/chapter3_GAN/3.4stylegan2/paper.md"
      - StyleGAN3: "book/chapter3_GAN/3.5stylegan3/paper.md"
      - StyleGAN T: "book/chapter3_GAN/3.6styleganT/paper.md"
      - R3GAN: "book/chapter3_GAN/3.7R3Gan/paper.md"
  - Diffusion:
      - Introduction: "book/chapter4_diffusion/4.1introduction.md"
      - DDPM: "book/chapter4_diffusion/4.2DDPM.md"
  - Generation Theory:
      - Maximal Likelihood: "book/chapter5_generation_theory/5.1MLE.md"
      - Manifold Hypothesis: "book/chapter5_generation_theory/manifold_hypothesis.md"
  - Energy Based Models:
      - Introduction: "book/chapter6_ebm/introduction.md"
      - Score Function: "book/chapter6_ebm/score_function.md"
      - Sampling: "book/chapter6_ebm/sampling.md"
      - Contrastive Divergence: "book/chapter6_ebm/cd.md"
      - Score Matching: "book/chapter6_ebm/score_matching.md"

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate  # 集成页内目录
extra:
  navigation:
    collapse: true  # 左侧导航可折叠
  toc:
    placement: right  # 将目录放在右侧

# theme:
#   name: gitbook
# extra_css:
#   - styles/custom.css
plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true   # 在标题旁添加可点击的链接
      toc_depth: 2      # 设置目录深度，例如只显示 h2 和 h3

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js