site_name: "Generative AI: From Start to Surrender"
nav:
  - "Home": index.md
  - Introduction:
      - Terms: "book/chapter1_Introduction/1.1terminology.md"
      - Fourier Transform: "book/chapter1_Introduction/1.2fourier_transform.md"
      - Signal Processing: "book/chapter1_Introduction/1.3signal_processing.md"
  - VAE:
      - VAE Introduction: "book/chapter2_VAE/2.1introduction.md"
  - GANs:
      - PGGAN: "book/chapter3_GAN/3.2pggan/paper.md"
      - StyleGAN: "book/chapter3_GAN/3.3stylegan/paper.md"
      - StyleGAN2: "book/chapter3_GAN/3.4stylegan2/paper.md"
      - StyleGAN3: "book/chapter3_GAN/3.5stylegan3/paper.md"
theme:
  name: gitbook

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js