# Combined Model Configuration for Stable Diffusion Web Interface

models:

  animagine-xl-4:
    display_name: "Animagine-XL 4"
    description: "An improved version of Animagine-XL"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config:
      repo_id: "cagliostrolab/animagine-xl-4.0"
      custom_pipeline: lpw_stable_diffusion_xl
      add_watermarker: False
      use_safetensors: True
    groups:
      - "Stable Diffusion Versions"
  sd-v1.0:
    display_name: "Stable Diffusion v1.0"
    description: "Original release version"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config: {}   # No pipeline config available
    groups:
      - "Stable Diffusion Versions"

  sd-v1.1:
    display_name: "Stable Diffusion v1.1"
    description: "Early version of Stable Diffusion"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config:
      repo_id: "CompVis/stable-diffusion-v1-1"
      type: standard
      safety_checker: true
      requires_safety_checker: true
    groups:
      - "Stable Diffusion Versions"

  sd-v1.2:
    display_name: "Stable Diffusion v1.2"
    description: "Improved version with better image quality"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config:
      repo_id: "CompVis/stable-diffusion-v1-2"
      type: standard
      safety_checker: true
      requires_safety_checker: true
    groups:
      - "Stable Diffusion Versions"

  sd-v1.3:
    display_name: "Stable Diffusion v1.3"
    description: "Enhanced version with better prompting capabilities"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config:
      repo_id: "CompVis/stable-diffusion-v1-3"
      type: standard
      safety_checker: true
      requires_safety_checker: true
    groups:
      - "Stable Diffusion Versions"

  sd-v1.5:
    display_name: "Stable Diffusion v1.5"
    description: "Most widely used stable version"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config:
      repo_id: "runwayml/stable-diffusion-v1-5"
      type: standard
      safety_checker: true
      requires_safety_checker: true
    groups:
      - "Stable Diffusion Versions"
  sd-xl-1.0:
    display_name: "Stable Diffusion XL v1.0"
    description: "Original release version"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 7.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 100
        default: 50
        step: 1
      height:
        min: 512
        max: 1024
        default: 512
        step: 64
      width:
        min: 512
        max: 1024
        default: 512
        step: 64
    config:
      repo_id: stabilityai/stable-diffusion-xl-base-1.0
      torch_dtype: float16
      use_safetensors: True
      variant: fp16
    groups:
      - "Stable Diffusion Versions"
  sd-v2.0:
    display_name: "Stable Diffusion v2.0"
    description: "Major update with improved quality"
    parameters:
      guidance_scale:
        min: 1
        max: 20
        default: 8.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 150
        default: 60
        step: 1
      height:
        min: 256
        max: 1024
        default: 768
        step: 64
      width:
        min: 256
        max: 1024
        default: 768
        step: 64
    config:
      repo_id: "stabilityai/stable-diffusion-2"

    groups:
      - "Stable Diffusion Versions"

  sd-v3.0:
    display_name: "Stable Diffusion v3.0"
    description: "Next generation capabilities"
    parameters:
      guidance_scale:
        min: 1
        max: 25
        default: 9.0
        step: 0.5
      num_inference_steps:
        min: 20
        max: 200
        default: 75
        step: 1
      height:
        min: 512
        max: 1536
        default: 1024
        step: 128
      width:
        min: 512
        max: 1536
        default: 1024
        step: 128
    config:
      repo_id: "stabilityai/stable-diffusion-3-medium-diffusers"
      torch_dtype: float16
    groups:
      - "Stable Diffusion Versions"
  sd-v3.5-quant:
    display_name: "Stable Diffusion v3.5 Quantized"
    description: "Latest version with best performance"
    parameters:
      ui_controls:
        show_prompt: true
        show_negative_prompt: true
        show_dimensions: true
        show_guidance_scale: true
        show_steps: true
        show_quantization: true
      guidance_scale:
        min: 1
        max: 25
        default: 4.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 200
        default: 100
        step: 1
      height:
        min: 512
        max: 1536
        default: 1024
        step: 128
      width:
        min: 512
        max: 1536
        default: 1024
        step: 128
    config:
      repo_id: "stabilityai/stable-diffusion-3-medium-diffusers"
      torch_dtype: float16
      quantization_config: {}
    groups:
      - "Stable Diffusion Versions"

  sd-v3.5:
    display_name: "Stable Diffusion v3.5"
    description: "Latest version with best performance"
    parameters:
      ui_controls:
        show_prompt: true
        show_negative_prompt: true
        show_dimensions: true
        show_guidance_scale: true
        show_steps: true
        show_quantization: true
      guidance_scale:
        min: 1
        max: 25
        default: 4.5
        step: 0.5
      num_inference_steps:
        min: 20
        max: 200
        default: 40
        step: 1
      height:
        min: 512
        max: 1536
        default: 1024
        step: 128
      width:
        min: 512
        max: 1536
        default: 1024
        step: 128
      negative_prompt:
        type: string
        default: ""
        description: "Optional negative prompt to guide the image generation away from certain characteristics"
    config:
      repo_id: "stabilityai/stable-diffusion-3.5-medium"
      torch_dtype: float16
      use_safetensors: true
    groups:
      - "Stable Diffusion Versions"

  flux1-schnell:
    display_name: "FLUX.1 Schnell"
    description: "Fast experimental model"
    parameters:
      guidance_scale:
        min: 1
        max: 30
        default: 10.0
        step: 0.5
      num_inference_steps:
        min: 20
        max: 200
        default: 100
        step: 1
      height:
        min: 512
        max: 2048
        default: 1024
        step: 128
      width:
        min: 512
        max: 2048
        default: 1024
        step: 128
    config:
      repo_id: "black-forest-labs/FLUX.1-schnell"
      torch_dtype: float16
    groups:
      - "Latest Models"