# Model parameters and configurations for Stable Diffusion web interface

# Generation parameters for each model
model_parameters:
  sd-v1.0: &sd_v1_base
    guidance_scale:
      min: 1
      max: 20
      default: 7.5
      step: 0.5
    num_inference_steps:
      min: 20
      max: 100
      default: 50
      step: 1
    height:
      min: 512
      max: 1024
      default: 512
      step: 64
    width:
      min: 512
      max: 1024
      default: 512
      step: 64

  sd-v1.1: *sd_v1_base
  sd-v1.2: *sd_v1_base
  sd-v1.3: *sd_v1_base
  sd-v1.5: *sd_v1_base

  sd-v2.0:
    guidance_scale:
      min: 1
      max: 20
      default: 8.5
      step: 0.5
    num_inference_steps:
      min: 20
      max: 150
      default: 60
      step: 1
    height:
      min: 256
      max: 1024
      default: 768
      step: 64
    width:
      min: 256
      max: 1024
      default: 768
      step: 64

  sd-v3.0:
    guidance_scale:
      min: 1
      max: 25
      default: 9.0
      step: 0.5
    num_inference_steps:
      min: 20
      max: 200
      default: 75
      step: 1
    height:
      min: 512
      max: 1536
      default: 1024
      step: 128
    width:
      min: 512
      max: 1536
      default: 1024
      step: 128

  sd-v3.5:
    # UI Control - which inputs to show
    ui_controls:
      show_prompt: true
      show_negative_prompt: true
      show_dimensions: true
      show_guidance_scale: true
      show_steps: true
      show_quantization: true
    # Model Parameters
    guidance_scale:
      min: 1
      max: 25
      default: 4.5
      step: 0.5
    num_inference_steps:
      min: 20
      max: 200
      default: 40
      step: 1
    height:
      min: 512
      max: 1536
      default: 1024
      step: 128
    width:
      min: 512
      max: 1536
      default: 1024
      step: 128
    use_quantized:
      type: boolean
      default: false
      description: Use 4-bit quantization for reduced memory usage
    negative_prompt:
      type: string
      default: ""
      description: Optional negative prompt to guide the image generation away from certain characteristics


  flux:
    guidance_scale:
      min: 1
      max: 30
      default: 10.0
      step: 0.5
    num_inference_steps:
      min: 20
      max: 200
      default: 100
      step: 1
    height:
      min: 512
      max: 2048
      default: 1024
      step: 128
    width:
      min: 512
      max: 2048
      default: 1024
      step: 128

  animagine-xl-4:
    guidance_scale:
      min: 1
      max: 30
      default: 4.0
      step: 0.5
    num_inference_steps:
      min: 20
      max: 200
      default: 50
      step: 1
    cfg_trunc_ratio:
      min: 0
      max: 1
      default: 0.25
      step: 0.1
    cfg_normalization:
      type: bool
      default: True

    height:
      min: 512
      max: 2048
      default: 1024
      step: 128
    width:
      min: 512
      max: 2048
      default: 1024
      step: 128

  lumina-2:
    guidance_scale:
      min: 1
      max: 30
      default: 12.0
      step: 0.5
    num_inference_steps:
      min: 25
      max: 200
      default: 100
      step: 1
    height:
      min: 512
      max: 2048
      default: 1024
      step: 128
    width:
      min: 512
      max: 2048
      default: 1024
      step: 128

# Model pipeline configurations
model_configs:
  animagine-xl-4:
    repo_id: cagliostrolab/animagine-xl-4.0
    torch_dtype: float16
    use_safetensors: False
    custom_pipeline: lpw_stable_diffusion_xl
    add_watermarker: False


  lumina-2:
    repo_id: Alpha-VLLM/Lumina-Image-2.0
    torch_dtype: float16

  sd-v1.1: &sd_v1_config
    repo_id: CompVis/stable-diffusion-v1-1
    type: standard
    safety_checker: true
    requires_safety_checker: true

  sd-v1.2:
    <<: *sd_v1_config
    repo_id: CompVis/stable-diffusion-v1-2

  sd-v1.3:
    <<: *sd_v1_config
    repo_id: CompVis/stable-diffusion-v1-3

  sd-v1.5:
    <<: *sd_v1_config
    repo_id: runwayml/stable-diffusion-v1-5

  sd-v2.0:
    repo_id: stabilityai/stable-diffusion-2
    type: standard
    safety_checker: true
    requires_safety_checker: true

  sd-v3.0:
    repo_id: stabilityai/stable-diffusion-3-medium
    type: standard
    safety_checker: true
    requires_safety_checker: true
    torch_dtype: float16
    variant: fp16

  sd-v3.5:
    repo_id: stabilityai/stable-diffusion-3.5-medium
    torch_dtype: float16
    use_safetensors: true

  flux:
    repo_id: black-forest-labs/FLUX.1-schnell
    torch_dtype: float16
    device_map: balanced
    max_memory: {0:"11GiB", 1:"11GiB", "cpu":"20GiB"}